name: surface_example
description: Example usage of Surface and Bouncy Ball.
version: 0.5.0
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  surface:
    path: ../

flutter:
  uses-material-design: true
