name: surface
description: Shapeable, layered, intrinsincally animated container with convenient access to blurs, InkResponse, and HapticFeedback; plus a number of customization parameters.
version: 0.0.3+2
repository: https://github.com/Zabadam/surface
issue_tracker: https://github.com/Zabadam/surface/issues

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
