name: surface
description: >
  Surface for content. Highly customizable.
  Convenient access to blurring filters;
  easy morphing, animated shape crafting;
  and painless inter/reactive user experiences.

version: 0.5.0
repository: https://github.com/Zabadam/surface
issue_tracker: https://github.com/Zabadam/surface/issues

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  xl: ^0.9.1
  ball: ^0.1.2
  animated_styled_widget: ^0.2.9

dev_dependencies:
  very_good_analysis: ^2.0.0

flutter: null
