name: surface
description: Shapeable, layered, intrinsincally animated container with convenient access to blurry ImageFilters, InkResponse, and HapticFeedback.
version: 0.3.0+1
repository: https://github.com/Zabadam/surface
issue_tracker: https://github.com/Zabadam/surface/issues
# +8

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  ball: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
